[features]
seeds = false
[programs.devnet]
postfeedapp = "79GRqHSs8MPinewuYuaSyQgTYD1WruUguy8JvRdMLe7T"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/clement/.config/solana/id.json" //change path for your particular id json path

[scripts]
test = "yarn run mocha -t 1000000 tests/"